"""base

Revision ID: 9020e29455d1
Revises: 
Create Date: 2025-05-22 04:56:19.749034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9020e29455d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('segment_infobox_hash', sa.String(), nullable=False),
    sa.Column('segment_category_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprite_segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('segment_path_hash', sa.String(), nullable=False),
    sa.Column('segment_license_hash', sa.String(), nullable=False),
    sa.Column('segment_attribution_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprite_segments')
    op.drop_table('entity_segments')
    # ### end Alembic commands ###
